### ISSUE TITLE
QOS != 0 gives exception

### ISSUE THREAD

**Issue by alanaquilina** [sabuhish/fastapi-mqtt#22]
Hello,

When publishing with QOS of 1 or 2 I get the following stack trace

Traceback (most recent call last):
  File "e:\code\python\pythontest\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "e:\code\python\pythontest\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "e:\code\python\pythontest\venv\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "e:\code\python\pythontest\venv\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "e:\code\python\pythontest\venv\lib\site-packages\fastapi\routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "e:\code\python\pythontest\venv\lib\site-packages\fastapi\routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File ".\main.py", line 60, in func
    await fast_mqtt.publish("test", "Hello from Fastapi", qos=1) #publishing mqtt topic
  File "e:\code\python\pythontest\venv\lib\site-packages\fastapi_mqtt\fastmqtt.py", line 226, in publish
    return await self.loop.run_in_executor(self.executor, func)
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "e:\code\python\pythontest\venv\lib\site-packages\gmqtt\client.py", line 291, in publish
    self._persistent_storage.push_message_nowait(mid, package)
  File "e:\code\python\pythontest\venv\lib\site-packages\gmqtt\storage.py", line 12, in push_message_nowait
    return asyncio.ensure_future(self.push_message(mid, raw_package))
  File "C:\Python38\lib\asyncio\tasks.py", line 660, in ensure_future
    loop = events.get_event_loop()
  File "C:\Python38\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
C:\Python38\lib\asyncio\base_events.py:1860: RuntimeWarning: coroutine 'HeapPersistentStorage.push_message' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
**************************************************************************************************************************************

Using QOS of 0 works fine

I took the example on the site and change the config to my server and managed to reproduce it.  Here it is:

from fastapi_mqtt.fastmqtt import FastMQTT
from fastapi import FastAPI
from fastapi_mqtt.config import MQQTConfig
import ssl

mqtt_config = MQQTConfig()

def config():
    server_cert = <PATH TO FILE>
    client_cert = <PATH TO FILE>
    client_key = <PATH TO FILE>

    context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=server_cert)
    context.load_cert_chain(certfile=client_cert, keyfile=client_key)

    mqtt_config.ssl = context
    mqtt_config.password = <MY PASSWORD>
    mqtt_config.username = <MY USERNAME>
    mqtt_config.host = <MY SERVER>
    mqtt_config.port = 8883

config()

fast_mqtt = FastMQTT(
    config=mqtt_config
)

app = FastAPI()

fast_mqtt.init_app(app)

@fast_mqtt.on_connect()
def connect(client, flags, rc, properties):
    fast_mqtt.client.subscribe("/mqtt") #subscribing mqtt topic 
    print("Connected: ", client, flags, rc, properties)

@fast_mqtt.subscribe("mqtt/+/temperature", "mqtt/+/humidity")
async def home_message(client, topic, payload, qos, properties):
    print("temperature/humidity: ", topic, payload.decode(), qos, properties)
    return 0

@fast_mqtt.on_message()
async def message(client, topic, payload, qos, properties):
    print("Received message: ",topic, payload.decode(), qos, properties)
    return 0

@fast_mqtt.on_disconnect()
def disconnect(client, packet, exc=None):
    print("Disconnected")

@fast_mqtt.on_subscribe()
def subscribe(client, mid, qos, properties):
    print("subscribed", client, mid, qos, properties)

@app.get("/")
async def func():
    await fast_mqtt.publish("test", "Hello from Fastapi", qos=1) #publishing mqtt topic

    return {"result": True,"message":"Published" }

**Comment by sabuhish** [comment]
@alanaquilina Thank you for the report. I have used QOS 0,1,2 everything was perfectly working. Could we figure out what broker do you use for testing? As I see you are using windows for testing, can try to check this on Linux machine to see if the error still raises.
Interesting error raises from asyncio library of python.

**Comment by alanaquilina** [comment]
Hello,

First of all thanks for your reply!  

I am using Mosquito 1.5.7 on a pi 4.  

I tried the same code on my PI and got the same error.  
I removed the SSL and got the same error

Might be worth noting that the connection is downgrading to MQTT 3.11

Thanks
Alan

**Comment by sabuhish** [comment]
Hi,
This might be the version of Mosquito you are using. is there are any possibility you can upgrade it?  I have used the version above 2 works fine. 

Also, one more thing to test, can you change the version in config parameter to 4. fastapi-mqtt uses gmqtt module on top of it.
https://github.com/wialon/gmqtt/blob/master/gmqtt/mqtt/constants.py#L53

**Comment by alanaquilina** [comment]
I upgraded Mosquitto to 2.0.10 and used both v5 and v4 in the client version.  Same error on QOS != 0 .

**Comment by sabuhish** [comment]
I am trying to produce the solution, let me I will update you.

**Comment by sabuhish** [comment]
I have found very the issue occurs. Actually, I have tested QoS with client subscribe not publish. 
I have submitted PR to [gmqtt-PR](https://github.com/wialon/gmqtt/pull/126). Once it is merged will release it with the new version. 

Thanks for finding this.

**Comment by alanaquilina** [comment]
Thank you for fixing!
    On Saturday, 3 April 2021, 19:22:53 CEST, Sabuhi ***@***.***> wrote:  
 
 


I have found very the issue occurs. Actually, I have tested QoS with client subscribe not publish.
I have submitted PR to gmqtt-PR. Once it is merged will release it with the new version.

Thanks for finding this.

**Comment by sabuhish** [comment]
This should now work at the latest version, could please check and let me know.I have updated documentation as well.

**Comment by alanaquilina** [comment]
Confirmed Working!  Thanks a lot!
    On Tuesday, 6 April 2021, 19:27:10 CEST, Sabuhi ***@***.***> wrote:  
 
 


This should now work at the latest version, could please check and let me know.I have updated documentation as well.
