### ISSUE TITLE
FastAPI Application error....ERROR:    Application startup failed. Exiting. TimeoutError: [Errno 10060] Connect call failed (mqtt broker ip,port) connecting to a mqtt broker

### ISSUE THREAD

**Issue by sreesoumyajajs** [sabuhish/fastapi-mqtt#50]
Issue:

TimeoutError: [Errno 10060] Connect call failed ('mqtt_brokerip,mqtt_brokerport)

ERROR:    Application startup failed. Exiting.
ERROR:uvicorn.error:Application startup failed. Exiting.

Time out error connecting to a mqtt broker using fastapi_mqtt library and the fastapi application is exiting.

Error Log
=======
INFO:     Started server process [24304]
INFO:uvicorn.error:Started server process [24304]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
WARNING:  Used broker version is 5
WARNING:uvicorn.error:Used broker version is 5
ERROR:    Traceback (most recent call last):
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\starlette\routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\starlette\routing.py", line 540, in __aenter__
    await self._router.startup()
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\starlette\routing.py", line 622, in startup
    await handler()
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\fastapi_mqtt\fastmqtt.py", line 277, in startup
    await self.connection()
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\fastapi_mqtt\fastmqtt.py", line 129, in connection
    await self.client.connect(self.client._host,self.client._port,self.client._ssl,self.client._keepalive,version)
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\gmqtt\client.py", line 225, in connect
    self._connection = await self._create_connection(
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\gmqtt\client.py", line 241, in _create_connection
    connection = await MQTTConnection.create_connection(host, port, ssl, clean_session, keepalive)
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\gmqtt\mqtt\connection.py", line 27, in create_connection
    transport, protocol = await loop.create_connection(MQTTProtocol, host, port, ssl=ssl)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python39\lib\asyncio\selector_events.py", line 500, in sock_connect
    return await fut
  File "C:\Program Files\Python39\lib\asyncio\selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ()

ERROR:uvicorn.error:Traceback (most recent call last):
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\starlette\routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\starlette\routing.py", line 540, in __aenter__
    await self._router.startup()
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\starlette\routing.py", line 622, in startup
    await handler()
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\fastapi_mqtt\fastmqtt.py", line 277, in startup
    await self.connection()
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\fastapi_mqtt\fastmqtt.py", line 129, in connection
    await self.client.connect(self.client._host,self.client._port,self.client._ssl,self.client._keepalive,version)
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\gmqtt\client.py", line 225, in connect
    self._connection = await self._create_connection(
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\gmqtt\client.py", line 241, in _create_connection
    connection = await MQTTConnection.create_connection(host, port, ssl, clean_session, keepalive)
  File "D:\python_samples\fastapi_framework\venv\lib\site-packages\gmqtt\mqtt\connection.py", line 27, in create_connection
    transport, protocol = await loop.create_connection(MQTTProtocol, host, port, ssl=ssl)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python39\lib\asyncio\selector_events.py", line 500, in sock_connect
    return await fut
  File "C:\Program Files\Python39\lib\asyncio\selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ()

ERROR:    Application startup failed. Exiting.
ERROR:uvicorn.error:Application startup failed. Exiting.

**Comment by sabuhish** [comment]
but I dont see any code you provide, it is the error not from library, it is most probably you have connections issues.

**Comment by sreesoumyajajs** [comment]
Thank you for the reply.

Please find the code which I am running . 
When there is connection issues, say not able to connect after time out , I am getting the following error. Could you please tell me how to handle socket timeout issues using fastapi_mqtt  library

ERROR: Application startup failed. Exiting.
ERROR:uvicorn.error:Application startup failed. Exiting.


Code:
============
from fastapi import FastAPI,Body
from fastapi_mqtt import FastMQTT, MQQTConfig

mqtt_config = MQQTConfig(host = mqtt_host,
    port= mqtt_port,
    keepalive = 60,
    username= gUsername,
    password= gPassword)

app = FastAPI()

app.parseThreadRunning = True

fast_mqtt = FastMQTT(config=mqtt_config) 
fast_mqtt.init_app(app)



@fast_mqtt.on_connect()
def connect(client, flags, rc, properties):
      pass

@fast_mqtt.on_message()
async def message(client, topic, payload, qos, properties):
    pass

@app.on_event("startup")
async def startup_event():
    
   app.parseThreadRunning = True
   app.parseThread = threading.Thread(target=start_message_parsing)
   app.parseThread.start()


@app.on_event("shutdown")
async def shutdown_event():
   
   print("Entered: FastAPI shutdown event")
   app.parseThreadRunning = False
   if app.parseThread.is_alive():      
   	print("Waiting for message parsing thread to stop")
   	app.parseThread.join()

      

if __name__ == '__main__':
    uvicorn.run("main:app", host="0.0.0.0", port=8000,reload=True)

**Comment by sabuhish** [comment]
there is nothing I can do about it, it is more likely a connection socket error, fastapi-mqtt is not able to connect given mqtt host, this is not on the high level of the library can be solved, we are able to connect without any issues to mqtt hosts.

**Comment by sreesoumyajajs** [comment]
OK.Thank you

**Comment by sabuhish** [comment]
@marvleaf could you please clarify your response? deleting Settings should not be the solution. What is the problem with port variable?

**Comment by sabuhish** [comment]
@ftapajos I understand your concern about your problem, I think implementing a health endpoint would be much better, because in this way your health endpoint of MQTT broker will depend on fastapi app, it will wait MQTT container to get up and be healthy. 

Normally databases also depends on app, runs first, like redis, mongo or postgresdb they should be healthy and then the application itself should take a start.

What we can implement re-connect feature in case of failure. I need to do research about it. Closing this issue because,  
it is a connection error, not library error.
