### ISSUE TITLE
Will message functionality and example broken

### ISSUE THREAD

**Issue by ajstewart** [sabuhish/fastapi-mqtt#53]
When trying to use the last will message I found that the functionality is broken which can also be seen when running the example provided in the repo:

```
❯ uvicorn examples.app_will_message:app --reload
INFO:     Will watch for changes in these directories: ['/Users/user/github/fastapi-mqtt']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [4334] using StatReload
INFO:     on_connect handler accepted
INFO:     on_message handler accepted
INFO:     on_subscribe handler accepted
INFO:     Started server process [4336]
INFO:     Waiting for application startup.
WARNING:  Used broker version is 5
ERROR:    Traceback (most recent call last):
  File "/Users/user/miniforge3/envs/fastapi-mqtt/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/Users/user/miniforge3/envs/fastapi-mqtt/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/Users/user/miniforge3/envs/fastapi-mqtt/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/Users/user/github/fastapi-mqtt/./fastapi_mqtt/fastmqtt.py", line 218, in startup
    await self.connection()
  File "/Users/user/github/fastapi-mqtt/./fastapi_mqtt/fastmqtt.py", line 124, in connection
    await self.client.connect(
  File "/Users/user/miniforge3/envs/fastapi-mqtt/lib/python3.10/site-packages/gmqtt/client.py", line 228, in connect
    await self._connection.auth(self._client_id, self._username, self._password, will_message=self._will_message,
  File "/Users/user/miniforge3/envs/fastapi-mqtt/lib/python3.10/site-packages/gmqtt/mqtt/connection.py", line 61, in auth
    await self._protocol.send_auth_package(client_id, username, password, self._clean_session,
  File "/Users/user/miniforge3/envs/fastapi-mqtt/lib/python3.10/site-packages/gmqtt/mqtt/protocol.py", line 114, in send_auth_package
    pkg = package.LoginPackageFactor.build_package(client_id, username, password, clean_session,
  File "/Users/user/miniforge3/envs/fastapi-mqtt/lib/python3.10/site-packages/gmqtt/mqtt/package.py", line 70, in build_package
    connect_flags |= 0x04 | ((will_message.qos & 0x03) << 3) | ((will_message.retain & 0x01) << 5)
TypeError: unsupported operand type(s) for &: 'str' and 'int'
```

Digging in I found this is because of two reasons:

* https://github.com/sabuhish/fastapi-mqtt/blob/856a0027ed232ad92f87c78024cf3022e469b0a3/fastapi_mqtt/fastmqtt.py#L79-L83 here the last will delay interval is being declared without `will_delay_interval=` which should be done as per the example over in `gmqtt`: https://github.com/wialon/gmqtt/blob/190d12156890efcfc5099fea0f7ef3ce072c4a27/examples/will_message.py#L43.
* The typing for `will_delay_interval` is set as a string in the pydantic model: https://github.com/sabuhish/fastapi-mqtt/blob/856a0027ed232ad92f87c78024cf3022e469b0a3/fastapi_mqtt/config.py#L57

**Comment by sabuhish** [comment]
Hi @ajstewart, you are right, I missed this part, thanks for finding out and solving this issue. I will merge your changes to the master. Good job!
